# Generated by Django 3.0 on 2022-03-26 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20220324_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='good_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='擅长'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_tab',
            field=models.BooleanField(default=False, verbose_name='是否为推荐医生'),
        ),
    ]
