# Generated by Django 3.0 on 2022-04-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220326_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, verbose_name='病况描述')),
                ('name', models.CharField(max_length=10, verbose_name='患者姓名')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=6, verbose_name='性别')),
                ('supplement', models.CharField(max_length=256, verbose_name='补充细节')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department', verbose_name='会诊科室')),
            ],
            options={
                'verbose_name': '患者信息',
                'verbose_name_plural': '患者信息',
            },
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
    ]
