# Generated by Django 3.0 on 2022-03-31 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0002_auto_20220324_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfav',
            options={'ordering': ['-add_time'], 'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='userleavingmessage',
            options={'ordering': ['-add_time'], 'verbose_name': '用户留言', 'verbose_name_plural': '用户留言'},
        ),
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='subject',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=10, verbose_name='真实姓名')),
                ('mobile', models.IntegerField(default='', max_length=11, verbose_name='手机号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '个人中心',
                'verbose_name_plural': '个人中心',
                'ordering': ['id'],
            },
        ),
    ]
