# Generated by Django 3.0 on 2022-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220324_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecat',
            options={'ordering': ['-add_time'], 'verbose_name': '知识科普区', 'verbose_name_plural': '知识科普区'},
        ),
        migrations.RemoveField(
            model_name='knowledgecat',
            name='name',
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='body',
            field=models.TextField(verbose_name='标签或知识区主体'),
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '知识详情')], verbose_name='类目级别'),
        ),
    ]
