# Generated by Django 3.0 on 2022-03-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220324_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecat',
            options={'ordering': ['-id'], 'verbose_name': '知识科普区分类', 'verbose_name_plural': '知识科普区分类'},
        ),
        migrations.RemoveField(
            model_name='knowledgecat',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='knowledgecat',
            name='body',
        ),
        migrations.AddField(
            model_name='knowledgecat',
            name='name',
            field=models.CharField(default='疾病', max_length=20, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], verbose_name='类目级别'),
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='知识区文章')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.KnowledgeCat', verbose_name='分类id')),
            ],
            options={
                'verbose_name': '知识区文章',
                'verbose_name_plural': '知识区文章',
                'ordering': ['-id'],
            },
        ),
    ]
