# Generated by Django 3.0 on 2022-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20220325_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecat',
            options={'ordering': ['id'], 'verbose_name': '知识科普区', 'verbose_name_plural': '知识科普区'},
        ),
        migrations.AddField(
            model_name='knowledgecat',
            name='body',
            field=models.TextField(null=True, verbose_name='知识区文章'),
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
