# Generated by Django 3.0 on 2022-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20220325_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecat',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
