# Generated by Django 3.0 on 2022-03-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220326_1951'),
        ('article', '0006_auto_20220325_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecat',
            name='depart',
            field=models.ManyToManyField(blank=True, null=True, related_name='departs', to='users.Department', verbose_name='相关科室'),
        ),
    ]
