# Generated by Django 3.0 on 2022-03-26 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20220324_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_knowledgecat_depart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aticle',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.KnowledgeCat', verbose_name='文章分类'),
        ),
    ]
