# Generated by Django 3.0 on 2022-03-29 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20220326_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='知识区文章'),
        ),
        migrations.AlterField(
            model_name='knowledgecat',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
