# Generated by Django 3.0 on 2022-03-29 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20220329_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 20, 46, 53, 881450), verbose_name='创建时间'),
        ),
    ]
